# Generated by Django 5.0.1 on 2024-01-23 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_bill_products'),
        ('clients', '0002_alter_client_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='clients.client'),
        ),
    ]
